apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-api-monitor
  namespace: airport-platform
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend-api
  namespaceSelector:
    matchNames:
      - airport-platform
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
