name: CI - Build Three-Tier Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t backend-api:${{ github.sha }} ./backend

      - name: Build frontend image
        run: docker build -t frontend:${{ github.sha }} ./frontend

      - name: Show images
        run: docker images